# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'vagrant-aws'

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = 'aws-dummy'
  # Specify AWS provider configuration
  config.vm.provider 'aws' do |aws, override|
    # Read AWS authentication information from environment variables
    aws.access_key_id = ENV['AWS_ACCESS_KEY_ID']
    aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']

    # Specify SSH keypair to use
    aws.keypair_name = 'gp-ssh-keypair'

    # Specify region, AMI ID, and security group(s)
    aws.region = 'eu-west-2'
    aws.ami = 'ami-4d3a2e29'
    aws.security_groups = ['default']

    # Specify username and private key path
    override.ssh.username = 'ubuntu'
    override.ssh.private_key_path = '~/.ssh/gp-ssh-keypair'
  end

  config.vm.provision "shell", path: "bootstrap.sh"
end
